str = "Welcome to python programming"
print("1",str.capitalize())
print("2",str.upper())
print("3",str.lower())
print("4",str.casefold())
print("5",str.center(34,"*"))
print("6",str.count("a"))
print("7",str.encode())
print("8",str.endswith("programming"))
print("8",str.endswith("is"))
print("9",str.expandtabs(3))
print("10",str.find("to"))
print("11",str.replace(" python","java"))
